[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "/.netlify/functions/api"
  REACT_APP_SERVER_URL = "https://namas-architecture.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"